# Generated by Django 4.2.11 on 2024-07-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='plan_paid',
            new_name='is_approved',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='plan_expiry_date',
        ),
    ]
