# Generated by Django 4.2.11 on 2024-05-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontactdetails',
            name='companyreg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
