# Generated by Django 4.2.11 on 2024-07-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('NAU', 'Normal App User'), ('FOU', 'Fleet Owner User'), ('COU', 'Cargo Owner User')], default='NAU', max_length=20),
        ),
    ]
