# Generated by Django 4.2.11 on 2024-04-28 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companycontactdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='companycontactdetails',
            name='comapnyEmail',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companycontactdetails',
            name='comapnyWebsite',
            field=models.URLField(max_length=100),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], max_length=20)),
                ('expiration_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
