# Generated by Django 4.2.11 on 2024-07-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_plan_paid_customuser_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontactdetails',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='companycontactdetails',
            name='plan_expiry_date',
        ),
        migrations.RemoveField(
            model_name='companycontactdetails',
            name='plan_paid',
        ),
    ]
