# Generated by Django 4.2.11 on 2024-07-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('accounts', '0003_remove_companycontactdetails_plan_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyContactDetails',
            new_name='Company',
        ),
        migrations.RenameModel(
            old_name='CompanyMembership',
            new_name='CompanyMember',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_approved',
        ),
    ]
