# Generated by Django 4.2.11 on 2024-04-30 13:55

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontactdetails',
            name='company',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=75, scale=None, size=[300, 300], upload_to='comapny/logo'),
        ),
    ]
