# Generated by Django 4.2.11 on 2024-05-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_cargo_owner',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_fleet_owner',
        ),
        migrations.AddField(
            model_name='companycontactdetails',
            name='company_type',
            field=models.CharField(choices=[('Fleet Company', 'Fleet Company'), ('Cargo Company', 'Cargo Company')], default='Fleet Company', max_length=20),
        ),
    ]
