# Generated by Django 4.2.11 on 2024-05-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_is_cargo_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontactdetails',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
