# Generated by Django 4.2.11 on 2024-04-28 20:40

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=75, scale=None, size=[500, 300], upload_to='vehicles/images')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=100)),
                ('platenumber', models.CharField(max_length=100)),
                ('isInsuared', models.BooleanField(default=True)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicleimage')),
                ('vehicleTypes', models.ManyToManyField(related_name='vehicles', to='fleet.vehicletype')),
            ],
        ),
    ]
