# Generated by Django 4.2.11 on 2024-05-08 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_companycontactdetails_is_approved'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.companycontactdetails'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
