# Generated by Django 4.2.11 on 2024-06-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_vehicle_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='platenumber',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
