# Generated by Django 4.2.11 on 2024-06-10 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('updates', '0002_alter_update_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectedupdatesbyuser',
            options={'verbose_name': 'User Subscription', 'verbose_name_plural': 'User Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='update',
            options={'verbose_name': 'Update', 'verbose_name_plural': 'Updates'},
        ),
        migrations.AlterModelOptions(
            name='updatetype',
            options={'verbose_name': 'Update Type', 'verbose_name_plural': 'Update Types'},
        ),
        migrations.AlterModelOptions(
            name='updateview',
            options={'verbose_name': 'Update View', 'verbose_name_plural': 'Update Views'},
        ),
        migrations.RenameField(
            model_name='update',
            old_name='isapproved',
            new_name='is_approved',
        ),
        migrations.AlterField(
            model_name='selectedupdatesbyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
