# Generated by Django 4.2.11 on 2024-07-13 16:38

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_unit', models.CharField(choices=[('kg', 'Kilograms'), ('ltr', 'Liters')], default='kg', max_length=3)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo', models.CharField(max_length=255)),
                ('fragile', models.BooleanField(default=False)),
                ('temperature_sensitive', models.BooleanField(default=False)),
                ('special_handling_instructions', models.TextField(blank=True, null=True)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_contact', models.CharField(max_length=255)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CargoTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_info', to='cargo.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='CargoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=75, scale=None, size=[500, 300], upload_to='cargo/images')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cargo.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='CargoDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cargo/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_documents', to='cargo.cargo')),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='cargo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='cargo.cargotype'),
        ),
    ]
