# Generated by Django 4.2.11 on 2024-04-28 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimensions', models.CharField(max_length=50)),
                ('fragile', models.BooleanField(default=False)),
                ('temperature_sensitive', models.BooleanField(default=False)),
                ('special_handling_instructions', models.TextField(blank=True)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_contact', models.CharField(max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('cargo_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.cargotype')),
                ('sender_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
