# Generated by Django 4.2.11 on 2024-05-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='actual_delivery_date',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='pickupdate',
        ),
    ]
