# Generated by Django 4.2.11 on 2024-05-06 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargo', '0002_cargodocument_alter_cargo_slug_alter_cargotype_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='cargo',
            field=models.CharField(default='Laguage name', max_length=50),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cargo_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargo.cargotype'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='sender_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
