# Generated by Django 4.2.11 on 2024-05-06 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_cargo_cargo_alter_cargo_cargo_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pickupdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
